### ISSUE TITLE
Erro ao importar planilha de dados

### ISSUE THREAD

**Issue by zedomel** [BioComp-USP/rebipp-system#36]
```
2023-07-11T14:21:42.036903+00:00 app[web.1]: Request received GET 2023-07-11T14:21:42.036Z /api/v1/table/publish?adminTableId=1RQwi75GzGWVxCoHKVOiUCdS1AnTqzP8ms-5kP9rSNRI&url=https://docs.google.com/spreadsheets/d/1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5/edit?usp=sharing&ouid=113208252282714247197&rtpof=true&sd=true
2023-07-11T14:21:42.037420+00:00 app[web.1]: [2023-07-11T14:21:42.037Z] PUBLISH  https://docs.google.com/spreadsheets/d/1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5/edit?usp=sharing
2023-07-11T14:21:42.216627+00:00 app[web.1]: The API returned an error: Error: This operation is not supported for this document
2023-07-11T14:21:42.220263+00:00 app[web.1]: [2023-07-11T14:21:42.218Z] ERROR ON PUBLISH Error: This operation is not supported for this document
2023-07-11T14:21:42.220264+00:00 app[web.1]:     at Request._callback (/app/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:85:15)
2023-07-11T14:21:42.220264+00:00 app[web.1]:     at self.callback (/app/node_modules/googleapis/node_modules/request/request.js:187:22)
2023-07-11T14:21:42.220265+00:00 app[web.1]:     at Request.emit (node:events:513:28)
2023-07-11T14:21:42.220266+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/googleapis/node_modules/request/request.js:1044:10)
2023-07-11T14:21:42.220266+00:00 app[web.1]:     at Request.emit (node:events:513:28)
2023-07-11T14:21:42.220266+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/googleapis/node_modules/request/request.js:965:12)
2023-07-11T14:21:42.220267+00:00 app[web.1]:     at IncomingMessage.emit (node:events:525:35)
2023-07-11T14:21:42.220270+00:00 app[web.1]:     at endReadableNT (node:internal/streams/readable:1359:12)
2023-07-11T14:21:42.220270+00:00 app[web.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
2023-07-11T14:21:42.220271+00:00 app[web.1]:   code: 400,
2023-07-11T14:21:42.220271+00:00 app[web.1]:   errors: [
2023-07-11T14:21:42.220271+00:00 app[web.1]:     {
2023-07-11T14:21:42.220289+00:00 app[web.1]:       message: 'This operation is not supported for this document',
2023-07-11T14:21:42.220289+00:00 app[web.1]:       domain: 'global',
2023-07-11T14:21:42.220290+00:00 app[web.1]:       reason: 'failedPrecondition'
2023-07-11T14:21:42.220290+00:00 app[web.1]:     }
2023-07-11T14:21:42.220290+00:00 app[web.1]:   ]
2023-07-11T14:21:42.220290+00:00 app[web.1]: }
2023-07-11T14:21:42.396879+00:00 app[web.1]: [2023-07-11T14:21:42.396Z] rebipp-system mongo connected successfully
2023-07-11T14:21:42.510327+00:00 app[web.1]: [2023-07-11T14:21:42.510Z] 
2023-07-11T14:21:42.510339+00:00 app[web.1]: [2023-07-11T14:21:42.510Z] 
2023-07-11T14:21:42.510379+00:00 app[web.1]: [2023-07-11T14:21:42.510Z]  true 128SFltBPse_qao9Yobkw5eCavPjNjMqSfgeBRz8kQ8Q 1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5
2023-07-11T14:21:42.510401+00:00 app[web.1]: [2023-07-11T14:21:42.510Z] 
2023-07-11T14:21:42.510422+00:00 app[web.1]: [2023-07-11T14:21:42.510Z]  true 1LDH6gwXex8DobBprtu045ImiRZvDPqfZHIuhMOvsRF8 1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5
2023-07-11T14:21:42.510435+00:00 app[web.1]: [2023-07-11T14:21:42.510Z] 
2023-07-11T14:21:42.510455+00:00 app[web.1]: [2023-07-11T14:21:42.510Z]  true 1LDH6gwXex8DobBprtu045ImiRZvDPqfZHIuhMOvsRF8 1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5
2023-07-11T14:21:42.510467+00:00 app[web.1]: [2023-07-11T14:21:42.510Z] 
2023-07-11T14:21:42.510590+00:00 app[web.1]: [2023-07-11T14:21:42.510Z]  true 1LDH6gwXex8DobBprtu045ImiRZvDPqfZHIuhMOvsRF8 1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5
2023-07-11T14:21:42.510607+00:00 app[web.1]: [2023-07-11T14:21:42.510Z] 
2023-07-11T14:21:42.510630+00:00 app[web.1]: [2023-07-11T14:21:42.510Z]  false 1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5 1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5
2023-07-11T14:56:08.620581+00:00 heroku[web.1]: Idling
2023-07-11T14:56:08.685762+00:00 heroku[web.1]: State changed from up to down
2023-07-11T14:56:09.373744+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2023-07-11T14:56:09.538629+00:00 heroku[web.1]: Process exited with status 143
```

Planilha: [https://docs.google.com/spreadsheets/d/1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5/edit#gid=236077029](https://docs.google.com/spreadsheets/d/1cwHP6kId6u6oaEEk0BSXVhmrflXz9N_5/edit#gid=236077029)

**Comment by zedomel** [comment]
Precisava dar permissão ao usuário de sistema.
